#define ERR_CAPTION						100
#define ERR_NO_INSTALL_PERM				101
#define ERR_NO_UNINSTALL_PERM			102
#define ERR_READ_SETUP_XML				103
#define ERR_BAD_SETUP_XML				104
#define ERR_BAD_SETUP_APP_INFO			105
#define ERR_BAD_SETUP_BDE_INFO			106
#define ERR_BAD_SETUP_ALIAS_INFO		107
#define ERR_BAD_SETUP_UNINSTALL_INFO	108
#define ERR_BAD_SETUP_FILES_INFO		109
#define ERR_FAILED_ALIAS				110
#define ERR_FAILED_BDE					111
#define	ERR_FAILED_CREATE				112
#define	ERR_BAD_SETUP_RESOURCE_INFO		113


#define INSTALL_CAPTION					200
#define INSTALL_START					201
#define INSTALL_CHECK					202
#define INSTALL_COPY					203
#define INSTALL_BDE						204
#define INSTALL_MENU					205
#define INSTALL_FINISH					206
#define INSTALL_END						207
#define INSTALL_EXEC					208

#define UNINSTALL_CAPTION				300
#define UNINSTALL_START					301
#define UNINSTALL_END					302
#define UNINSTALL_CLOSE					303
#define UNINSTALL_MESSAGE				304




 