// Do not edit. This file is machine generated by the Resource DLL Wizard.
//---------------------------------------------------------------------------
#define PACKAGE __declspec(package)
#define USERC(FileName) extern PACKAGE _Dummy
#define USERES(FileName) extern PACKAGE _Dummy
#define USEFORMRES(FileName, FormName, AncestorName) extern PACKAGE _Dummy
#pragma hdrstop
int _turboFloat;
//---------------------------------------------------------------------------
/*ITE*/ /*DFMFileType*/ /*C\CRESD\SOURCE\GAKLIB\REPOSITORY\Config.dfm*/
/*ITE*/ /*DFMFileType*/ /*C\CRESD\SOURCE\GAKLIB\REPOSITORY\DirSelFrm.dfm*/
/*ITE*/ /*DFMFileType*/ /*InstallerMain.dfm*/
/*ITE*/ /*DFMFileType*/ /*vcl\DBLOGDLG.dfm*/
/*ITE*/ /*DFMFileType*/ /*vcl\DBPWDLG.dfm*/
/*ITE*/ /*RCFileType*/ /*setup_err.rc*/
/*ITE*/ /*RCFileType*/ /*..\..\OBJECT\INSTALLER\Setup_DRC.rc*/
//---------------------------------------------------------------------------
USEFORMRES("C\CRESD\SOURCE\GAKLIB\REPOSITORY\Config.dfm", ConfigDataModule, DataModule); /* TDataModule: DesignClass */
USEFORMRES("C\CRESD\SOURCE\GAKLIB\REPOSITORY\DirSelFrm.dfm", DirectorySelector, Form); /* TForm: DesignClass */
USEFORMRES("InstallerMain.dfm", InstallerForm, Form); /* TForm: DesignClass */
USEFORMRES("vcl\DBLOGDLG.dfm", LoginDialog, Form); /* Form: DesignClass */
USEFORMRES("vcl\DBPWDLG.dfm", PasswordDialog, Form); /* Form: DesignClass */
USERC("setup_err.rc");
USERC("..\..\OBJECT\INSTALLER\Setup_DRC.rc");
USERES("Setup.res");
//---------------------------------------------------------------------------
#define DllEntryPoint
