// Do not edit. This file is machine generated by the Resource DLL Wizard.
//---------------------------------------------------------------------------
#define PACKAGE __declspec(package)
#define USERC(FileName) extern PACKAGE _Dummy
#define USERES(FileName) extern PACKAGE _Dummy
#define USEFORMRES(FileName, FormName, AncestorName) extern PACKAGE _Dummy
#pragma hdrstop
int _turboFloat;
//---------------------------------------------------------------------------
/*ITE*/ /*DFMFileType*/ /*UnInstallerMain.dfm*/
/*ITE*/ /*RCFileType*/ /*setup_err.rc*/
/*ITE*/ /*RCFileType*/ /*..\..\OBJECT\INSTALLER\Uninstall_DRC.rc*/
//---------------------------------------------------------------------------
USEFORMRES("UnInstallerMain.dfm", UninstallMainForm, Form); /* TForm: DesignClass */
USERC("setup_err.rc");
USERC("..\..\OBJECT\INSTALLER\Uninstall_DRC.rc");
USERES("Uninstall.res");
//---------------------------------------------------------------------------
#define DllEntryPoint
